# Generated by Django 4.0.5 on 2023-01-09 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
